{{ if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pib-secrets
stringData:
  BlobStorage__ConnectionString: {{ .Values.secrets.blobStorageConnectionString }}
  AppConfig__ConnectionString: {{ .Values.secrets.appConfigConnectionString }}
{{ end }}  