apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: pib
    type: mongodb
spec:
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: pib
        type: mongodb
    spec: 
      containers:
        - name: mongodb-container
          image: mongo:latest
          ports:
            - containerPort: 27017
  replicas: 1
  selector:
    matchLabels:
      type: mongodb