version: '3.8'
services:
  api:
    image: backend
    build: ../../backend
    ports: 
      - 7196:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Mongo__ConnectionString=mongodb://mongo-db:27017
    depends_on:
      - mongo-db
      - seq
  web:
    image: frontend
    build: ../../frontend
    ports: 
      - 3000:80
  mongo-db:
    image: mongo:latest
    container_name: pib-mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db
  seq:
    image: datalust/seq:latest
    container_name: pib-seq
    ports:
      - 5341:80
    volumes:
      - ./seq-data:/data
    environment:
      - ACCEPT_EULA=Y
