apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: pib
    type: webapp
spec:
  template:
    metadata:
      name: webapp-pod
      labels:
        app: pib
        type: webapp
    spec: 
      containers:
        - name: webapp-container
          image: frontend:local2
          ports:
            - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      type: webapp