apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-api-deployment
  labels:
{{ include "labels" . | indent 4 }}
spec:
  template:
    metadata:
      name: api-pod
      labels:
{{ include "labels" . | indent 8 }}
        tier: api
    spec:
      containers:
        - name: api-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ .Values.global.environment }}"
            - name: Mongo__ConnectionString
              value: "{{ .Values.mongo.connectionString }}"
          envFrom:
            {{- if .Values.k8sSecrets.enabled }}
            - secretRef:
                name: pib-secrets
            {{- end}}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      service: {{ .Chart.Name }}
      tier: api