version: '3.8'
services:
    mongodb_container:
        image: mongo:latest
        container_name: pib-mongo
        ports:
            - 27017:27017
        volumes:
            - ./mongodb-data:/data/db
    seq_container:
        image: datalust/seq:latest
        container_name: pib-seq
        ports:
            - 5341:80
        volumes:
            - ./seq-data:/data
        environment:
          - ACCEPT_EULA=Y